extends SceneTree
const State = preload("res://scripts/game_state.gd")
const Levels = preload("res://scripts/levels.gd")
const DIRECTIONS = {"U": Vector2i.UP, "R": Vector2i.RIGHT, "D": Vector2i.DOWN, "L": Vector2i.LEFT}
var failures := 0

func check(condition: bool, description: String) -> void:
	if not condition:
		failures += 1
		printerr("FAIL: " + description)

func _init() -> void:
	var fixtures: Array = JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/expert_solutions.json"))
	var state = State.new()
	for i in Levels.DATA.size():
		var data: Dictionary = Levels.DATA[i]
		state.setup(data.map, data.get("require_all", false), data.get("time_limit", 0.0))
		if data.get("require_all", false):
			var fixture: Dictionary = fixtures[i - 15]
			check(fixture.map == data.map, "Expert audit matches actual map")
			for point in fixture.route.slice(1):
				var target := Vector2i(int(point[0]), int(point[1]))
				var result: String = state.move(target - state.player)
				check(result in ["moved", "won"], "%s expert route step: %s" % [data.name, result])
			check(state.tiles_left() == 0, "Expert wins only after clearing all tiles")
			check(state.crystals_left == 0 and state.keys == 0, "Expert keys spent, crystals collected")
		elif data.has("solution"):
			for step in data.solution:
				var result: String = state.move(DIRECTIONS[step])
				check(result in ["moved", "won"], "%s adventure step: %s" % [data.name, result])
		else:
			var route: Array[Vector2i] = state.shortest_route()
			check(not route.is_empty(), "Classic level %d solvable" % (i + 1))
			for cell in route: state.move(cell - state.player)
		check(state.won, "Level %d reaches win" % (i + 1))
		check(state.visited.size() == state.moves + 1, "Every visit unique, including start")
		check(state.move(Vector2i.LEFT) == "finished", "Win locks movement")
	state.setup(["S.F", "...", "..."])
	check(state.move(Vector2i.LEFT) == "wall", "Boundary blocked")
	check(state.moves == 0, "Rejected move not counted")
	check(state.move(Vector2i(1, 1)) == "invalid", "Diagonal blocked")
	state.move(Vector2i.RIGHT)
	check(state.move(Vector2i.LEFT) == "visited", "Start cannot be revisited")
	check(state.moves == 1, "Visited move not counted")
	state.move(Vector2i.DOWN)
	state.move(Vector2i.LEFT)
	check(state.move(Vector2i.UP) == "visited", "Trail cannot be revisited")
	state.setup(["S.F", ".##"])
	check(state.move(Vector2i.DOWN) == "stuck", "Dead end detected")
	check(state.move(Vector2i.UP) == "finished", "Dead end locks movement")
	state.setup(["SF", ".."], true)
	check(state.move(Vector2i.RIGHT) == "goal_locked", "Expert early finish blocked")
	check(state.moves == 0 and state.player == Vector2i.ZERO and state.tiles_left() == 3, "Early finish leaves state unchanged")
	state.move(Vector2i.DOWN)
	state.move(Vector2i.RIGHT)
	check(not state.goal_locked(), "Expert flag unlocks after clearing floor")
	check(state.move(Vector2i.UP) == "won", "Expert flag last wins")
	state.setup(["S.F", ".##"], true)
	state.move(Vector2i.RIGHT)
	check(state.stuck and not state.won, "Locked flag is not a legal escape")
	state.setup(["SDF", "K.."])
	check(state.move(Vector2i.RIGHT) == "door_locked" and state.moves == 0, "Door rejects without key")
	state.move(Vector2i.DOWN)
	check(state.keys == 1, "Key collected")
	state.move(Vector2i.RIGHT)
	state.move(Vector2i.UP)
	check(state.keys == 0 and state.player == Vector2i(1, 0), "Door consumes exactly one key")
	check(state.move(Vector2i.RIGHT) == "won", "Door path works")
	state.setup(["SF", "G."])
	check(state.move(Vector2i.RIGHT) == "goal_locked", "Crystal locks flag in adventure too")
	state.move(Vector2i.DOWN)
	check(state.crystals_left == 0, "Crystal consumed once")
	check(state.move(Vector2i.UP) == "visited" and state.crystals_left == 0, "Cannot recollect crystal")
	state.move(Vector2i.RIGHT)
	check(state.move(Vector2i.UP) == "won", "Crystal unlocks flag")
	state.setup(["S1#", "#1F"])
	check(state.move(Vector2i.RIGHT) == "moved", "Portal move legal")
	check(state.player == Vector2i(1, 1) and state.moves == 2, "Portal uses both ends atomically")
	check(state.visited.has(Vector2i(1, 0)) and state.visited.has(Vector2i(1, 1)), "Both portal ends consumed")
	check(state.move(Vector2i.UP) == "visited", "Cannot teleport back")
	check(state.move(Vector2i.RIGHT) == "won", "Can exit portal toward goal")
	state.setup(["S1F"])
	check(state.move(Vector2i.RIGHT) == "portal_blocked" and state.moves == 0, "Unpaired portal rejected safely")
	state.setup(["S1#", "#1F"])
	state.visited[Vector2i(1, 1)] = true
	check(state.move(Vector2i.RIGHT) == "portal_blocked" and state.player == Vector2i.ZERO, "Consumed portal exit rejected atomically")
	state.setup(["SII.", "###F"])
	check(state.move(Vector2i.RIGHT) == "moved" and state.player == Vector2i(3, 0), "Ice forces full slide to floor")
	check(state.moves == 3 and state.visited.size() == 4, "Every ice tile consumed")
	check(state.move(Vector2i.LEFT) == "visited", "Cannot slide back over trail")
	check(state.move(Vector2i.DOWN) == "won", "Can turn after slide")
	state.setup(["SII#", "##F#"])
	state.move(Vector2i.RIGHT)
	check(state.player == Vector2i(2, 0), "Ice stops at wall")
	check(state.move(Vector2i.DOWN) == "won", "Can turn at blocked ice")
	state.setup(["SIIF"])
	check(state.move(Vector2i.RIGHT) == "won", "Slide can reach finish")
	state.setup(["SIID", "##F#"])
	state.move(Vector2i.RIGHT)
	check(state.player == Vector2i(2, 0) and state.keys == 0, "Ice cannot bypass locked door")
	state.setup(["S.F"], false, 2.0)
	check(not state.advance_time(1.0) and state.time_left == 1.0, "Timer counts down")
	check(state.advance_time(1.5) and state.stuck and state.time_left == 0, "Timeout ends level")
	check(state.move(Vector2i.RIGHT) == "finished", "Timeout locks input")
	state.setup(["SF"], false, 2.0)
	state.move(Vector2i.RIGHT)
	check(not state.advance_time(5.0) and state.won and not state.stuck, "Winning freezes timer")
	state.setup(["S.F", ".##"])
	check(not state.stuck and not state.won and state.moves == 0 and state.visited.size() == 1, "Restart resets state")
	check(not state.require_all and state.keys == 0 and state.crystals_left == 0 and state.portals.is_empty() and state.time_limit == 0, "Classic reset clears every special mechanic")
	check(state.move(Vector2i.RIGHT) == "moved", "Movement resumes after restart")
	print("Game tests: %d failures. All %d levels and special mechanics checked." % [failures, Levels.DATA.size()])
	quit(1 if failures else 0)
